/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import sistema_de_visitas.Conexao;

/**
 *
 * @author Luan Diniz
 */
public class carteira extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public carteira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpf_carteira = new javax.swing.JFormattedTextField();
        nome_carteira = new javax.swing.JFormattedTextField();
        paciente_carteira = new javax.swing.JFormattedTextField();
        acompanhando_visitando = new javax.swing.JFormattedTextField();
        voltar_remover = new javax.swing.JButton();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        sexo_carteira = new javax.swing.JFormattedTextField();
        idade_carteira = new javax.swing.JFormattedTextField();
        liberar_entrada = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        entrada_carteira = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        data_carteira = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        horario_carteira = new javax.swing.JFormattedTextField();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMITIR CARTEIRA");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        try {
            cpf_carteira.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf_carteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_carteiraActionPerformed(evt);
            }
        });
        getContentPane().add(cpf_carteira);
        cpf_carteira.setBounds(70, 50, 160, 22);

        nome_carteira.setEditable(false);
        nome_carteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_carteiraActionPerformed(evt);
            }
        });
        nome_carteira.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nome_carteiraPropertyChange(evt);
            }
        });
        getContentPane().add(nome_carteira);
        nome_carteira.setBounds(80, 130, 160, 22);

        paciente_carteira.setEditable(false);
        paciente_carteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_carteiraActionPerformed(evt);
            }
        });
        getContentPane().add(paciente_carteira);
        paciente_carteira.setBounds(150, 220, 170, 22);

        acompanhando_visitando.setEditable(false);
        acompanhando_visitando.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acompanhando_visitando.setText("ACOMPANHANDO");
        acompanhando_visitando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompanhando_visitandoActionPerformed(evt);
            }
        });
        getContentPane().add(acompanhando_visitando);
        acompanhando_visitando.setBounds(20, 220, 120, 22);

        voltar_remover.setText("VOLTAR");
        voltar_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_removerActionPerformed(evt);
            }
        });
        getContentPane().add(voltar_remover);
        voltar_remover.setBounds(150, 260, 90, 23);

        jFormattedTextField5.setEditable(false);
        jFormattedTextField5.setText("CPF");
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(20, 50, 40, 22);

        jFormattedTextField7.setEditable(false);
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField7.setText("NOME");
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField7);
        jFormattedTextField7.setBounds(20, 130, 50, 22);

        jFormattedTextField8.setEditable(false);
        jFormattedTextField8.setText("SEXO");
        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField8);
        jFormattedTextField8.setBounds(20, 160, 50, 22);

        jFormattedTextField9.setEditable(false);
        jFormattedTextField9.setText("IDADE");
        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField9);
        jFormattedTextField9.setBounds(20, 190, 50, 22);

        sexo_carteira.setEditable(false);
        sexo_carteira.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        sexo_carteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo_carteiraActionPerformed(evt);
            }
        });
        getContentPane().add(sexo_carteira);
        sexo_carteira.setBounds(80, 160, 80, 22);

        idade_carteira.setEditable(false);
        idade_carteira.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        idade_carteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idade_carteiraActionPerformed(evt);
            }
        });
        getContentPane().add(idade_carteira);
        idade_carteira.setBounds(80, 190, 80, 22);

        liberar_entrada.setText("LIBERAR ENTRADA");
        liberar_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberar_entradaActionPerformed(evt);
            }
        });
        getContentPane().add(liberar_entrada);
        liberar_entrada.setBounds(250, 260, 150, 23);

        consultar.setText("CONSULTAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(240, 50, 110, 23);

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setText("DATA AGENDADA");
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(260, 130, 111, 22);

        entrada_carteira.setEditable(false);
        getContentPane().add(entrada_carteira);
        entrada_carteira.setBounds(400, 190, 90, 22);

        jFormattedTextField2.setEditable(false);
        jFormattedTextField2.setText("HORARIO");
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(260, 160, 80, 22);

        data_carteira.setEditable(false);
        getContentPane().add(data_carteira);
        data_carteira.setBounds(380, 130, 90, 22);

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setText("ENTRADA LIBERADA");
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(260, 190, 130, 22);

        horario_carteira.setEditable(false);
        getContentPane().add(horario_carteira);
        horario_carteira.setBounds(350, 160, 90, 22);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_vs.jpeg"))); // NOI18N
        fundo.setMaximumSize(new java.awt.Dimension(0, 300));
        getContentPane().add(fundo);
        fundo.setBounds(0, -10, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpf_carteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_carteiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_carteiraActionPerformed

    private void nome_carteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_carteiraActionPerformed


// TODO add your handling code here:
       
    }//GEN-LAST:event_nome_carteiraActionPerformed

    private void paciente_carteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_carteiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_carteiraActionPerformed

    private void acompanhando_visitandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompanhando_visitandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acompanhando_visitandoActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void voltar_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_removerActionPerformed
    javax.swing.SwingUtilities.getWindowAncestor(voltar_remover).dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_voltar_removerActionPerformed

    private void nome_carteiraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nome_carteiraPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_carteiraPropertyChange

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void sexo_carteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo_carteiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexo_carteiraActionPerformed

    private void idade_carteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idade_carteiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idade_carteiraActionPerformed

    private void liberar_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberar_entradaActionPerformed
    if(entrada_carteira.getText().equals("sim")){
    JOptionPane.showMessageDialog(null, "A entrada já está liberada ! ");    
    }
    else{
            String jdbcUrl = "jdbc:mysql://localhost:3306/visitas?serverTimezone=America/Sao_Paulo";
            String username = "root";
            String password = "root";
                    
            try(Connection connection = DriverManager.getConnection(jdbcUrl, username, password)){
            
            String tabela = "visitas.acompanhantes_visitantes";
            Conexao conexao = new Conexao();
            
            String visitante=nome_carteira.getText();
            String paciente=paciente_carteira.getText();
            
            conexao.liberarEntrada(tabela, "sim", visitante, paciente, connection);
            entrada_carteira.setText("sim");
            JOptionPane.showMessageDialog(null, "Entrada Liberada ! ");

            
                                  
            }catch (SQLException e) {
            e.printStackTrace();}
               
    }
            
        
// TODO add your handling code here:
    }//GEN-LAST:event_liberar_entradaActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
               
        
            String jdbcUrl = "jdbc:mysql://localhost:3306/visitas?serverTimezone=America/Sao_Paulo";
            String username = "root";
            String password = "root";
            
            try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
        
            String cpf=cpf_carteira.getText();
                
            long id = 0;
            try {
            //transformando o cpf recebido em uma id    
            id = Long.parseLong(cpf);
        }   catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, insira um número válido no campo CPF.");
            return; // Retorna para evitar a execução do restante do código
        }
            String tabela = "visitas.acompanhantes_visitantes";
            //iniciando conexao com o banco de dados
            Conexao conexao = new Conexao ();
            //realizando uma busca no bando de dados pelo id (cpf que foi recebido anteriormente)
            ResultSet resultadoId=conexao.buscarCPF(tabela, id, connection);
            
            if (resultadoId.next()) {
            //se o cpf for encontrado, os dados vinculados a ele são recebidos    
              String nome = resultadoId.getString("nome");
              String sexo = resultadoId.getString("sexo");
              String idade = resultadoId.getString("idade");
              String categoria = resultadoId.getString("categoria");
              String paciente = resultadoId.getString("acompanhando_visitando");
              Date data= resultadoId.getDate("data_visita");
              String entrada = resultadoId.getString("entrada_liberada");
              String horario = resultadoId.getString("horario");
              
              //uma caixa de texto se adapta dependendo se a pessoa é um acompanahnte ou visitante
              if(categoria.equals("Acompanhante"))acompanhando_visitando.setText("ACOMPANHANDO");
              else acompanhando_visitando.setText("VISITANDO");
              
              //as caixas de texto são preenchidas com os dados do acompanhante/visitante
              nome_carteira.setText(nome);
              sexo_carteira.setText(sexo);
              idade_carteira.setText(idade);
              paciente_carteira.setText(paciente);
              data_carteira.setText(data.toString());
              entrada_carteira.setText(entrada);
              horario_carteira.setText(horario);              
            }  

            else {
              //se o cpf não for encontrado no banco de dados, é exibido um aviso e as caixas de texto são limpas  
              JOptionPane.showMessageDialog(null, "CPF não encontrado !");
              nome_carteira.setText("");
              paciente_carteira.setText("");
              sexo_carteira.setText("");

                        }
            } catch (SQLException e) {
            e.printStackTrace();}
    }              
            
            
       /* 



        // TODO add your handling code here:
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carteira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField acompanhando_visitando;
    private javax.swing.JButton consultar;
    private javax.swing.JFormattedTextField cpf_carteira;
    private javax.swing.JFormattedTextField data_carteira;
    private javax.swing.JFormattedTextField entrada_carteira;
    private javax.swing.JLabel fundo;
    private javax.swing.JFormattedTextField horario_carteira;
    private javax.swing.JFormattedTextField idade_carteira;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JButton liberar_entrada;
    private javax.swing.JFormattedTextField nome_carteira;
    private javax.swing.JFormattedTextField paciente_carteira;
    private javax.swing.JFormattedTextField sexo_carteira;
    private javax.swing.JButton voltar_remover;
    // End of variables declaration//GEN-END:variables
}
