/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import sistema_de_visitas.Conexao;

/**
 *
 * @author Luan Diniz
 */
public class historico_paciente extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public historico_paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        cpf_consulta = new javax.swing.JFormattedTextField();
        consultar = new javax.swing.JButton();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        nome_paciente = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_historico = new javax.swing.JTable();
        voltar_historico = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HISTORICO PACIENTE");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jFormattedTextField9.setEditable(false);
        jFormattedTextField9.setText("CPF DO PACIENTE");
        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField9);
        jFormattedTextField9.setBounds(40, 20, 130, 22);

        try {
            cpf_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(cpf_consulta);
        cpf_consulta.setBounds(180, 20, 170, 22);

        consultar.setText("BUSCAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(360, 20, 100, 23);

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setText("NOME DO PACIENTE");
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(40, 50, 130, 22);

        nome_paciente.setEditable(false);
        getContentPane().add(nome_paciente);
        nome_paciente.setBounds(180, 50, 170, 22);

        tabela_historico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOME", "CATEGORIA", "DATA", "HORARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_historico);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 420, 180);

        voltar_historico.setText("VOLTAR");
        voltar_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_historicoActionPerformed(evt);
            }
        });
        getContentPane().add(voltar_historico);
        voltar_historico.setBounds(193, 270, 90, 20);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_vs.jpeg"))); // NOI18N
        fundo.setMaximumSize(new java.awt.Dimension(0, 300));
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void cpf_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_consultaActionPerformed

    
 private void voltar_historicoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
                javax.swing.SwingUtilities.getWindowAncestor(voltar_historico).dispose();

    }
 
    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed

        String jdbcUrl = "jdbc:mysql://localhost:3306/visitas?serverTimezone=America/Sao_Paulo";
        String username = "root";
        String password = "root";

        DefaultTableModel modelo = (DefaultTableModel) tabela_historico.getModel();
                
        try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {

            String tabela = "visitas.paciente";
            String tabela1 = "acompanhantes_visitantes";
            
            long id = 0;
            
            try {
            //transformando o cpf que foi recebido em uma id    
            id = Long.parseLong(cpf_consulta.getText());
        }   catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, insira um número válido no campo CPF.");
            return; // Retorna para evitar a execução do restante do código
        }    
            //iniciando conexao com o banco de dados
            Conexao conexao = new Conexao();
            //realizando um busca no banco de dados pela id
            ResultSet resultadoId = conexao.buscarCPF(tabela, id, connection);            

            if (resultadoId.next()) {
                //recebendo o nome vinculado a id
                String nome = resultadoId.getString("nome");
                //exibindo na caixa de texto o nome encontrado               
                nome_paciente.setText(nome); 
                //chamdno o método que exibe na tabela todos os acompanhantes e visitas de um determinando paciente
                conexao.imprimirDadosPorNome(tabela1, connection, modelo, nome);
            }
            else {
                //exibindo um aviso caso o paciente não seja encontrado pelo id
                JOptionPane.showMessageDialog(null, "Paciente nao encontrado !");
                //limpando as caixas de texto
                cpf_consulta.setText("");
                nome_paciente.setText("");
                

            }
        } catch (SQLException e) {
            e.printStackTrace();}
        }

        /*

        // TODO add your handling code here:
    }//GEN-LAST:event_consultarActionPerformed

    private void voltar_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_historicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltar_historicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(historico_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(historico_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(historico_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(historico_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new historico_paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultar;
    private javax.swing.JFormattedTextField cpf_consulta;
    private javax.swing.JLabel fundo;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField nome_paciente;
    private javax.swing.JTable tabela_historico;
    private javax.swing.JButton voltar_historico;
    // End of variables declaration//GEN-END:variables
}
