/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sistema_de_visitas.Conexao;

/**
 *
 * @author Luan Diniz
 */
public class pesquisar_paciente extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public pesquisar_paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JLabel();
        cpf_consulta = new javax.swing.JFormattedTextField();
        nome_consulta = new javax.swing.JFormattedTextField();
        acompanhante_consulta = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        voltar_remover = new javax.swing.JButton();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        sexo_consulta = new javax.swing.JFormattedTextField();
        condicao_consulta = new javax.swing.JFormattedTextField();
        peso_consulta = new javax.swing.JFormattedTextField();
        consultar = new javax.swing.JButton();
        fundo1 = new javax.swing.JLabel();

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_vs.jpeg"))); // NOI18N
        fundo.setMaximumSize(new java.awt.Dimension(0, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PESQUISAR PACIENTE");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        try {
            cpf_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(cpf_consulta);
        cpf_consulta.setBounds(150, 50, 160, 22);

        nome_consulta.setEditable(false);
        nome_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_consultaActionPerformed(evt);
            }
        });
        nome_consulta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nome_consultaPropertyChange(evt);
            }
        });
        getContentPane().add(nome_consulta);
        nome_consulta.setBounds(80, 130, 180, 22);

        acompanhante_consulta.setEditable(false);
        acompanhante_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompanhante_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(acompanhante_consulta);
        acompanhante_consulta.setBounds(150, 220, 170, 22);

        jFormattedTextField4.setEditable(false);
        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField4.setText("ACOMPANHANTE");
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(20, 220, 120, 22);

        voltar_remover.setText("VOLTAR");
        voltar_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_removerActionPerformed(evt);
            }
        });
        getContentPane().add(voltar_remover);
        voltar_remover.setBounds(190, 260, 90, 23);

        jFormattedTextField5.setEditable(false);
        jFormattedTextField5.setText("CPF DO PACIENTE");
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(20, 50, 120, 22);

        jFormattedTextField6.setEditable(false);
        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField6.setText("CONDIÇÃO");
        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField6);
        jFormattedTextField6.setBounds(20, 100, 80, 22);

        jFormattedTextField7.setEditable(false);
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField7.setText("NOME");
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField7);
        jFormattedTextField7.setBounds(20, 130, 50, 22);

        jFormattedTextField8.setEditable(false);
        jFormattedTextField8.setText("SEXO");
        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField8);
        jFormattedTextField8.setBounds(20, 160, 50, 22);

        jFormattedTextField9.setEditable(false);
        jFormattedTextField9.setText("IDADE");
        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField9);
        jFormattedTextField9.setBounds(20, 190, 50, 22);

        sexo_consulta.setEditable(false);
        sexo_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        sexo_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(sexo_consulta);
        sexo_consulta.setBounds(80, 160, 80, 22);

        condicao_consulta.setEditable(false);
        condicao_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        condicao_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condicao_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(condicao_consulta);
        condicao_consulta.setBounds(110, 100, 80, 22);

        peso_consulta.setEditable(false);
        peso_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        peso_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(peso_consulta);
        peso_consulta.setBounds(80, 190, 80, 22);

        consultar.setText("CONSULTAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(320, 50, 110, 23);

        fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_vs.jpeg"))); // NOI18N
        fundo1.setMaximumSize(new java.awt.Dimension(0, 300));
        getContentPane().add(fundo1);
        fundo1.setBounds(0, -10, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpf_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_consultaActionPerformed

    private void nome_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_consultaActionPerformed


// TODO add your handling code here:
       
    }//GEN-LAST:event_nome_consultaActionPerformed

    private void acompanhante_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompanhante_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acompanhante_consultaActionPerformed

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void voltar_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_removerActionPerformed
    javax.swing.SwingUtilities.getWindowAncestor(voltar_remover).dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_voltar_removerActionPerformed

    private void nome_consultaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nome_consultaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_consultaPropertyChange

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void sexo_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexo_consultaActionPerformed

    private void condicao_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condicao_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_condicao_consultaActionPerformed

    private void peso_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_consultaActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        
            String jdbcUrl = "jdbc:mysql://localhost:3306/visitas?serverTimezone=America/Sao_Paulo";
            String username = "root";
            String password = "root";
            
            try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            
            long id = 0;
            try {
            //transformando o cpf recebido em uma id    
            id = Long.parseLong(cpf_consulta.getText());
        }   catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, insira um número válido no campo CPF.");
            return; // Retorna para evitar a execução do restante do código
        }
            
            String tabela = "visitas.paciente";
            //iniciando conexao com o banco de dados
            Conexao conexao = new Conexao();
            //realizando um busca no banco de dados pelo id recebido
            ResultSet resultadoId = conexao.buscarCPF(tabela, id, connection);
            
            if (resultadoId.next()) {
              //recebendo os dados vinculados ao id
              String estado = resultadoId.getString("estado");            
              String nome = resultadoId.getString("nome");
              String sexo = resultadoId.getString("sexo");
              String idade = resultadoId.getString("idade");
              String acompanhante = resultadoId.getString("acompanhante");
              
              //exibindo na caixa de texto os dados encontrados
              condicao_consulta.setText(estado);
              nome_consulta.setText(nome);
              acompanhante_consulta.setText(acompanhante);
              sexo_consulta.setText(sexo);
              peso_consulta.setText(idade);
                        } 
            else {
              //exibindo um aviso caso o paciente não for encontrado  
              JOptionPane.showMessageDialog(null, "Paciente nao encontrado !");
              //limpando as caixas de texto
              condicao_consulta.setText("");
              nome_consulta.setText("");
              acompanhante_consulta.setText("");
              sexo_consulta.setText("");
              peso_consulta.setText("");

                        }
            } catch (SQLException e) {
            e.printStackTrace();}
    }              
            
            
       /* 



        // TODO add your handling code here:
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesquisar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesquisar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesquisar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesquisar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesquisar_paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField acompanhante_consulta;
    private javax.swing.JFormattedTextField condicao_consulta;
    private javax.swing.JButton consultar;
    private javax.swing.JFormattedTextField cpf_consulta;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundo1;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JFormattedTextField nome_consulta;
    private javax.swing.JFormattedTextField peso_consulta;
    private javax.swing.JFormattedTextField sexo_consulta;
    private javax.swing.JButton voltar_remover;
    // End of variables declaration//GEN-END:variables
}
