/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import static java.lang.System.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Diniz
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrar = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        emitir_carteira = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        historico_paciente = new javax.swing.JButton();
        historico_geral = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TELA PRINCIPAL");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        cadastrar.setText("Cadastrar Acompanhante/Visitante");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(10, 140, 220, 23);

        pesquisar.setText("Pesquisar Paciente");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(270, 140, 220, 23);

        emitir_carteira.setText("Emitir Carteira");
        emitir_carteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emitir_carteiraActionPerformed(evt);
            }
        });
        getContentPane().add(emitir_carteira);
        emitir_carteira.setBounds(140, 220, 220, 23);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(140, 260, 220, 23);

        historico_paciente.setText("Historico Paciente");
        historico_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historico_pacienteActionPerformed(evt);
            }
        });
        getContentPane().add(historico_paciente);
        historico_paciente.setBounds(270, 180, 220, 23);

        historico_geral.setText("Historico Geral");
        historico_geral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historico_geralActionPerformed(evt);
            }
        });
        getContentPane().add(historico_geral);
        historico_geral.setBounds(10, 180, 220, 23);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_vs.jpeg"))); // NOI18N
        fundo.setMaximumSize(new java.awt.Dimension(0, 300));
        getContentPane().add(fundo);
        fundo.setBounds(0, -10, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        cadastro cadastro1 = new cadastro ();
        cadastro1.setSize(499, 300);
        cadastro1.setLocationRelativeTo(null);
        cadastro1.setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        pesquisar_paciente consulta1 = new pesquisar_paciente ();
        consulta1.setSize(600, 400);
        consulta1.setLocationRelativeTo(null);
        consulta1.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarActionPerformed

    private void emitir_carteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emitir_carteiraActionPerformed
        carteira carteira1 = new carteira ();
        carteira1.setSize(600, 400);
        carteira1.setLocationRelativeTo(null);
        carteira1.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_emitir_carteiraActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja sair ?","Confirmacao",JOptionPane.YES_NO_OPTION);
        if(opcao == JOptionPane.YES_OPTION){
            exit(0);
        }
        else{
            
        }
            
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void historico_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historico_pacienteActionPerformed
        historico_paciente historico1 = new historico_paciente ();
        historico1.setSize(600, 400);
        historico1.setLocationRelativeTo(null);
        historico1.setVisible(true);  
        
// TODO add your handling code here:
    }//GEN-LAST:event_historico_pacienteActionPerformed

    private void historico_geralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historico_geralActionPerformed
        historico_geral historico1 = new historico_geral ();
        historico1.setSize(600, 400);
        historico1.setLocationRelativeTo(null);
        historico1.setVisible(true);  
                // TODO add your handling code here:
    }//GEN-LAST:event_historico_geralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //new principal().setVisible(true);
                principal janela = new principal();

                // Definir o tamanho da janela (width, height)
                janela.setSize(600, 400);

                // Centralizar a janela na tela
                janela.setLocationRelativeTo(null);

                janela.setVisible(true);
               
            }
        });
    }   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton emitir_carteira;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton historico_geral;
    private javax.swing.JButton historico_paciente;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
